INSERT INTO util_beer_type (beer_type, description)
  VALUES
  ("American Lager", "Light in flavor, color, and alcohol content, but inexpensive and easy to produce."),
  ("Helles", "Commonly German, maltier than its pilsner cousins and bright gold in flavor."),
  ("German Pilsner", "Pale gold and medium in hoppiness. Slight maltiness."),
  ("Bohemian Pilsner", "Also known as Czech, straw colored and hoppy. Can be quite floral."),
  ("Amber American Lager", "Prevalent malt flavoring and hoppiness depending on the brewer. Often has a caramel color and aroma."),
  ("Oktoberfest", "A full-bodied beer, brewed for the famous German festival. If you see this attached to your favorite beer, prepare for a highly toasted flavor and more alcohol."),
  ("German Schwarzbier", "A dark beer that is light in flavor. They can be quite sweet."),
  ("Vienna Lager", "Austrian style lager, reddish in color, sweet and malty."),
  ("Bock", "A malty sweet beer with a dark copper color."),
  ("Doppelbock", "Stronger than bock, with a full body."),
  ("Weizenbock", "Wheat beer with a fruity, malty flavor."),
  ("Maibock", "A paler and hoppier bock, with a malt flavor. Brewed in May."),
  ("American Brown Ale", "A dark beer with less bitterness than porters and stouts. Rich caramel color and medium bodied profile."),
  ("English Brown Ale", "A nuttier and fuller body than its American counterpart. Often has a caramel aroma."),
  ("American Amber Ale", "A malty, medium bodied beer with caramel flavor and amber color"),
  ("American Pale Ale", "A medium bodied, hoppy beer with a light copper color."),
  ("Blonde Ale", "A well balanced beer with a full aroma. Can be malty or hoppy."),
  ("English Bitter", "Hoppiness presents a bitter flavor. Less alcoholic, and has a fruity note."),
  ("English Pale", "Strong hoppy flavor and sweet malt."),
  ("India Pale Ale", "A family of hoppy and floral beers."),
  ("American IPA", "Hoppy, herbal and citrus flavors.")
  ("Imperial IPA", "A stronger variant of the American IPA"),
  ("English IPA", "A less hoppy and alcoholic variety of IPA."),
  ("American Imperial Porter", "American imperial porters are dark in color, but lacking in burnt malt taste. They also boast a malty sweetness that goes well with chocolate and coffee."),
  ("English Brown Porter", "English brown porter is a dark beer that's similar to the American style, but usually with a lower alcohol content and less malt sweetness."),
  ("Robust Porter", "Robust porters are stronger and more bitter than a brown porter with a rich dark color and a subtle caramel flavor."),
  ("American Stout", "American stouts are dark beers that feature malt flavors working to create strong chocolate and coffee notes, but without overpowering hop bitterness."),
  ("American Imperial Stout", "American imperial stouts are strong dark beers with a malty flavor and a deep black color."),
  ("Oatmeal Stout", "As their name suggests, oatmeal stouts feature oatmeal in their malt blend. This adds smoothness and sweetness to the beer."),
  ("Milk Stout", "Lactose adds a sweet caramel or chocolate flavor to milk stouts"),
  ("Irish Dry Stout", "Irish dry stouts are dark beers; black in color with a bitterness that comes from roasted barley."),
  ("Belgian Pale Ale", "Belgian pale ale contains a toasted malt flavor that is subtle enough to not overpower the taste of the hops."),
  ("Belgian Dubbel", "Belgian dubbels feature rich and malty flavor with a spicy, fruity note."),
  ("Belgian Trippel", "Belgian trippels are lighter-bodied beers with a slight hoppy bitterness and a high alcohol content."),
  ("Belgian Quadrupel", "Belgian trippels are lighter-bodied beers with a slight hoppy bitterness and a high alcohol content."),
  ("Belgian Strong Dark Ale", "Belgian strong dark ale features a very high alcohol content with complex fruity flavors."),
  ("Belgian Saison", "Saisons (also known as farmhouse ales) have earthy notes and a medium hop flavor."),
  ("American Pale Wheat", "American pale wheat beer is pale in color, lower in alcohol content, and with a light bready flavor."),
  ("Belgian Witbier", "Witbier gets its name from its white color, and has a light, fruity flavor to match"),
  ("Berliner Weisse", "Tart, sour beer with a pale color. Sometimes raspberry syrup is added to dull the sour taste."),
  ("Dunkelweizen", "Dunkelweizen is a darker version of a Hefeweizen. These beers have a malty flavor with hints of banana."),
  ("Roggenweizen", "A rye based wheat beer that has a strong spice and malt flavor."),
  ("Hefeweizen", "Hefeweizen is a light colored wheat beer with a crisp taste that can sometimes have hints of cloves, light banana, or apples."),
  ("American Sour", "American sour beer packs a wild punch from certain bacteria that are introduced during the fermentation process."),
  ("Belgian Fruit Lambec", "Belgian fruit lambics are brewed with fruit to make an intense sweet and sour flavor."),
  ("Flanders Red Ale", "Flanders red ale evokes a malty, fruity flavor underneath a strong sour taste brought on by Lactobacillus bacteria during fermentation."),
  ("Belgian Gueuze", "Gueuzes are aged beers that give off a very strong sour flavor."),
  ("American Black Ale", "American black ales are dark in color and feature a malty, roasted flavor with medium to high hop bitterness. This style is sometimes called a black IPA."),
  ("Barrel-Aged Beer", "A barrel-aged beer is any type of beer that has been aged in a wooden barrel. Sometimes these barrels have been used to hold bourbon, wine, or other spirits, adding to the flavor of the beer."),
  ("Chocolate Beer", "Chocolate or cocoa can be added to any style (lager or ale) to form a delicious chocolate beer."),
  ("Coffee Beer", "A porter or stout that has strongly added coffee flavor. Can be achieved by steeping coffee beans or grounds, or mixing coffee into the beer during the fermentation process."),
  ("Fruit Beer", "Any fruit can be infused into any type of beer."),
  ("Vegetable Beer", "Any vegetable can be infused into any type of beer."),
  ("Rye Beer", "Rye beer often features malty, roasted flavors, with lower hop bitterness. Rye beers can be made as ales or as lagers, and will either take on a sweet or spicy flavor."),
  ("Session Beer", "Any style of beer can be brewed as a session beer, as sessions are simply less strong, more drinkable beers that are perfect for summertime consumption."),
  ("Smoke Beer", "Smoke beer is any beer that is brewed with malt that has been kilned over an open fire. The smoke adds a noticeable, but not overpowering flavor, which is inspired by traditional German rauchbier.")
  ("Scotch Ale", "A strong pale ale from Edinburgh in the 19th century. This was typical of the strong pale ales brewed in Britain at that time - mainly pale barley malt and moderate hopping, and were not that stylistically different to English Strong Ales or Barley Wines.")
